ARG TB_BASE_TAG=4.2.1.1
FROM thingsboard/tb-postgres:${TB_BASE_TAG}

# Metemos el .deb compilado por Maven y lo reinstalamos dentro de la imagen base
COPY docker/thingsboard.deb /tmp/thingsboard.deb
RUN dpkg -i /tmp/thingsboard.deb && rm -f /tmp/thingsboard.deb
