name: Build & Push ThingsBoard (brand)

on:
  push:
    branches: [ "brand-4.2" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build ThingsBoard artifacts
        run: mvn -B clean install -DskipTests -Dlicense.skip=true

      - name: Extract .deb to minimal rootfs for Docker build
        run: |
          DEB_PATH="1000 4 5 20 24 27 30 46 122 135 136 142 999 1000 1001ls -1 application/target/*.deb 2>/dev/null | head -n 1)"
          if [ -z "" ]; then
            echo "ERROR: No .deb found in application/target/"
            ls -la application/target || true
            exit 1
          fi

          rm -rf docker/rootfs docker/rootfs-min
          mkdir -p docker/rootfs docker/rootfs-min

          dpkg-deb -x "" docker/rootfs
          echo "Extracted: "

          # Copiamos solo lo necesario (evita conflictos con /lib, systemd, etc.)
          if [ -d docker/rootfs/usr/share/thingsboard ]; then
            mkdir -p docker/rootfs-min/usr/share
            cp -a docker/rootfs/usr/share/thingsboard docker/rootfs-min/usr/share/
          fi

          if [ -d docker/rootfs/etc/thingsboard ]; then
            mkdir -p docker/rootfs-min/etc
            cp -a docker/rootfs/etc/thingsboard docker/rootfs-min/etc/
          fi

          echo "rootfs-min top-level:";
          find docker/rootfs-min -maxdepth 3 -type d | sort | head -n 100


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (amd64 + arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.brand
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/tb-postgres-brand:4.2
          build-args: |
            TB_BASE_TAG=4.2.1.1
